version: '3'

tasks:

  dev:
    deps:
      - task: content-dev
      - task: site-dev
      - task: engine-dev

  build:
    cmds:
      - task: content-build
      - task: engine-build
      - task: site-build

  content-dev:
    watch: true
    sources:
      - './content/**/*.go'
    cmds:
      - cd content && go run main.go

  content-build:
    cmds:
      - cd content && go build main.go

  site-dev:
    cmds:
      - cd site && pnpm dev

  site-build:
    cmds:
      - cd site && pnpm build

  engine-dev:
    cmds:
      - cd engine && node cli

  engine-build:
      cmds:
        - cd engine && node cli build